name: Android CI Challenge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mobiledevops/android-sdk-image:34.0.0-jdk17
      options: --user 1001

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "Using build mode: debug"

    - name: Simulate multi-app builds
      run: |
        mkdir -p android_bundle/output/fakeapps

        echo '{"fake": "Simulated App 1"}' > android_bundle/output/fakeapps/FakeMessenger-debug.apk
        echo '{"fake": "Simulated App 2"}' > android_bundle/output/fakeapps/FakeScanner-debug.apk
        echo '{"fake": "Simulated App 3"}' > android_bundle/output/fakeapps/FakeControlPanel-debug.apk

        echo "Checksums:"
        sha1sum android_bundle/output/fakeapps/*.apk

    - name: Simulate JSON configuration
      run: |
        cat > android_bundle/output/fakeapps/installation.config.json <<EOF
        {
          "server_configuration": {
            "server_ip": "127.0.0.1",
            "site_code": "FAKE_SITE_001"
          },
          "apk_definitions": {
            "FakeControlPanel-debug.apk": {
              "package_name": "com.acme.controlpanel"
            },
            "FakeScanner-debug.apk": {
              "package_name": "com.foobar.qrscanner"
            },
            "FakeMessenger-debug.apk": {
              "package_name": "com.example.messenger"
            }
          }
        }
        EOF
        cat android_bundle/output/fakeapps/installation.config.json

    - name: Archive simulated build
      run: |
        zip -r signage-all.zip android_bundle/output/

    - uses: actions/upload-artifact@v4
      with:
        name: signage-bundle
        path: signage-all.zip
